primaryColor=#36a9e1
secondaryColor=#86C953
labelColor=#ffffff
hideWhenOffline=false
contactMail=admin@domain.com
loadingLabel=Cargando...
loginError=Error Login
chatHeader=Habla con nosotros
startInfo=Llena el formulario para comenzar
widgetWidth=340
widgetHeight=400
widgetOffset=50
mobileBreakpoint=550
maxConnections=5
messageSound=audio/default.mp3
startLabel=Iniciar
backLabel=Regresar
initMessageBody=Hola, en que te puedo ayudar?
initMessageAuthor=Operator
chatInputLabel=Escribe tu pregunta
timeDaysAgo=dias
timeHoursAgo=horas
timeMinutesAgo=minutos
timeSecondsAgo=segundos
offlineMessage=Operator fuera de linea
toggleSoundLabel=Efectos de sonido
toggleScrollLabel=Auto-scroll
toggleEmoticonsLabel=Emoticons
toggleAutoShowLabel=Auto-show
toggleFullscreenLabel=Toggle fullscreen
endChatLabel=Finalizar chat
endChatConfirmQuestion=Estas seguro?
endChatConfirm=Si
endChatCancel=Cancelar
contactHeader=Contactanos
contactInfo=Todos los operadores estan fuera de linea. Usa el formulario para enviar correo
contactNameLabel=Nombre
contactMailLabel=Email
contactQuestionLabel=Tu pregunta
contactSendLabel=Enviar
contactSuccessHeader=Mensaje enviado
contactSuccessMessage=Tu pregunta fue enviada, Gracias!
contactErrorHeader=Error
contactErrorMessage=Hubo un error al enviar tu pregunta
headerHeight=45
installed=1
autoShowWidgetAfter=10
autoShowWidget=true
askForMail=true
